//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dhgl2013Entities : DbContext
    {
        public dhgl2013Entities()
            : base("name=dhgl2013Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Area> T_Area { get; set; }
        public virtual DbSet<v_infolist> v_infolist { get; set; }
    
        public virtual int P_Article_Delete(Nullable<int> articleID, ObjectParameter returnValue)
        {
            var articleIDParameter = articleID.HasValue ?
                new ObjectParameter("ArticleID", articleID) :
                new ObjectParameter("ArticleID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Article_Delete", articleIDParameter, returnValue);
        }
    
        public virtual ObjectResult<P_Order_Total_Result> P_Order_Total(Nullable<int> oid)
        {
            var oidParameter = oid.HasValue ?
                new ObjectParameter("oid", oid) :
                new ObjectParameter("oid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_Order_Total_Result>("P_Order_Total", oidParameter);
        }
    
        public virtual int P_UserLogTime(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_UserLogTime", userIDParameter);
        }
    
        public virtual ObjectResult<P_UserSignValidate_Result> P_UserSignValidate(string userAccount, string pwd)
        {
            var userAccountParameter = userAccount != null ?
                new ObjectParameter("UserAccount", userAccount) :
                new ObjectParameter("UserAccount", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("Pwd", pwd) :
                new ObjectParameter("Pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_UserSignValidate_Result>("P_UserSignValidate", userAccountParameter, pwdParameter);
        }
    
        public virtual ObjectResult<P_UserSignWebValidate_Result> P_UserSignWebValidate(string userAccount, string pwd)
        {
            var userAccountParameter = userAccount != null ?
                new ObjectParameter("UserAccount", userAccount) :
                new ObjectParameter("UserAccount", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("Pwd", pwd) :
                new ObjectParameter("Pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_UserSignWebValidate_Result>("P_UserSignWebValidate", userAccountParameter, pwdParameter);
        }
    
        public virtual ObjectResult<T_Product_Recommend_Result> T_Product_Recommend(Nullable<int> lineSite)
        {
            var lineSiteParameter = lineSite.HasValue ?
                new ObjectParameter("LineSite", lineSite) :
                new ObjectParameter("LineSite", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<T_Product_Recommend_Result>("T_Product_Recommend", lineSiteParameter);
        }
    
        public virtual int V_Admin_Delete(Nullable<int> userID, ObjectParameter returnValue)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("V_Admin_Delete", userIDParameter, returnValue);
        }
    
        public virtual ObjectResult<V_AdminSignValidate_Result> V_AdminSignValidate(string userAccount, string pwd)
        {
            var userAccountParameter = userAccount != null ?
                new ObjectParameter("UserAccount", userAccount) :
                new ObjectParameter("UserAccount", typeof(string));
    
            var pwdParameter = pwd != null ?
                new ObjectParameter("Pwd", pwd) :
                new ObjectParameter("Pwd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<V_AdminSignValidate_Result>("V_AdminSignValidate", userAccountParameter, pwdParameter);
        }
    }
}
