//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tmall_CountryPackage
    {
        public int CPId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string CountryName { get; set; }
        public Nullable<int> PackageSorting { get; set; }
        public int PackageId { get; set; }
        public string PackageName { get; set; }
        public string TmallPackageName { get; set; }
        public Nullable<int> BaseShare { get; set; }
        public Nullable<int> ImgTag { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public Nullable<int> EffectivePackage { get; set; }
        public Nullable<int> PackageType { get; set; }
        public Nullable<bool> IsUrgent { get; set; }
        public Nullable<bool> IsKeFuMetering { get; set; }
        public Nullable<bool> IsVisaFee { get; set; }
        public Nullable<bool> IsFingerprintsOff { get; set; }
        public string CreateUserName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<bool> IsFuVisaFee { get; set; }
        public Nullable<bool> IsElectronicVisa { get; set; }
        public string ProgressType { get; set; }
    }
}
