//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tmall_Country
    {
        public int ID { get; set; }
        public string Tmall_ID { get; set; }
        public string CountryName { get; set; }
        public string VisaType { get; set; }
        public Nullable<bool> Enable { get; set; }
        public Nullable<bool> WeFingerprintToSend { get; set; }
        public Nullable<bool> WeToSend { get; set; }
        public Nullable<int> CountrySorting { get; set; }
        public Nullable<bool> EnableDelivery { get; set; }
        public string ProgressType { get; set; }
        public Nullable<int> SectorID { get; set; }
        public Nullable<bool> EnableDeliveryLockOf { get; set; }
    }
}
