//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tmall_Package
    {
        public int ID { get; set; }
        public Nullable<int> Huaxia_ID { get; set; }
        public string PackageName { get; set; }
        public Nullable<long> T_PackageId { get; set; }
        public string T_PackageName { get; set; }
        public string T_Type { get; set; }
        public Nullable<int> ImgTag { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public Nullable<int> Division { get; set; }
        public Nullable<byte> PackageType { get; set; }
    }
}
